const constants = {
  TRANSACTION_TYPES: {
    EXPENSE: 'expense',
    INCOME: 'income',
    SAVINGS: 'saving',
  },
};
const actions = {
  // users
  REQUEST_USERS_SUCCESS: 'REQUEST_USERS_SUCCESS',
  REQUEST_USERS_FAILURE: 'REQUEST_USERS_FAILURE',
  REQUEST_CURRENT_USER: 'REQUEST_CURRENT_USER',
  REQUEST_USER_UPDATE: 'REQUEST_USER_UPDATE',
  
  // signin
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
  REQUEST_SIGN_IN_SUCCESS: 'REQUEST_SIGN_IN_SUCCESS',
  REQUEST_SIGN_IN_FAILURE: 'REQUEST_SIGN_IN_FAILURE',
  REQUEST_LOGOUT: 'REQUEST_LOGOUT',

  // txns
  REQUEST_TRANSACTIONS: 'REQUEST_TRANSACTIONS',
  REQUEST_TRANSACTIONS_SUCCESS: 'REQUEST_TRANSACTIONS_SUCCESS',
  REQUEST_TRANSACTIONS_FAILURE: 'REQUEST_TRANSACTIONS_FAILURE',

  // recs
  REQUEST_RECOMMENDATIONS: 'REQUEST_RECOMMENDATIONS',
  REQUEST_RECOMMENDATIONS_SUCCESS: 'REQUEST_RECOMMENDATIONS_SUCCESS',
  REQUEST_RECOMMENDATIONS_FAILURE: 'REQUEST_RECOMMENDATIONS_FAILURE',

  // s3
  REQUEST_S3_UPLOAD: 'REQUEST_S3_UPLOAD',
  S3_UPLOAD_SUCCESS: 'S3_UPLOAD_SUCCESS',
  S3_UPLOAD_FAILURE: 'S3_UPLOAD_FAILURE',

  // analyse
  REQUEST_ANALYSE: 'REQUEST_ANALYSE',
  ANALYSE_SUCCESS: 'ANALYSE_SUCCESS',
  ANALYSE_FAILURE: 'ANALYSE_FAILURE',
};

const api = {
  BASE_URL: '/api',
  LOGIN: '/auth/signin',
  USER: '/user',
  TRANSACTION: '/transaction',
  RECOMMENDATION: '/recommendation',
  S3: '/s3',
  ANALYSER: 'https://receipt-analyzer-hyrpxvacda-uc.a.run.app',
};

export { constants, actions, api };
